version: "3.2"
services:
  judger:
    image: ccr.ccs.tencentyun.com/jiezi19971225/ahpuoj-judger:1.1.1
    container_name: ahpuojv2_judger
    restart: always
    tty: true
    volumes:
      - ${OJ_DATA_PATH_HOST}:${OJ_DATA_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}
      # - ${OJ_SCHEDULER_PATH_HOST}:${OJ_SCHEDULER_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}
    depends_on:
      - db
      - redis
      - rabbitmq
    entrypoint: /usr/local/bin/docker-entrypoint.sh
    privileged: true
  db:
    image: mysql:latest
    container_name: ahpuojv2_mysql
    restart: always
    ports:
      - "33060:3306"
    volumes:
      - /var/lib/mysql
      - ../sql/oj.sql:/docker-entrypoint-initdb.d/oj.sql
      - ../sql/casbin.sql:/docker-entrypoint-initdb.d/casbin.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      TZ: Asia/Shanghai

  redis:
    image: redis:latest
    container_name: ahpuojv2_redis
    restart: always
    ports:
      - "6379:6379"
    command: redis-server --requirepass ${REDIS_PASSWORD}

  fe:
    image: ccr.ccs.tencentyun.com/jiezi19971225/ahpuoj-fe:latest
    container_name: ahpuojv2_fe
    restart: always
    ports:
      - 80:80
    #   - 443:443
    volumes:
      - ${OJ_UPLOAD_PATH}:${OJ_UPLOAD_PATH_CONTAINER}${OJ_CODE_CONTAINER_FLAG}

  rabbitmq:
    image: rabbitmq:3.8.2-management
    container_name: ahpuojv2_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
      RABBITMQ_DEFAULT_VHOST:
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
